/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    'min-h-screen',
    'bg-gray-100',
    'bg-gray-900',
    'bg-white',
    'bg-gray-800',
    'bg-gray-700',
    'bg-gray-50',
    'text-white',
    'text-gray-800',
    'shadow-md',
    'shadow-lg',
    'shadow',
    'container',
    'mx-auto',
    'px-4',
    'py-4',
    'py-8',
    'p-6',
    'p-4',
    'p-2',
    'flex',
    'justify-between',
    'items-center',
    'space-x-4',
    'rounded-full',
    'rounded-lg',
    'rounded',
    'text-2xl',
    'text-xl',
    'font-bold',
    'font-semibold',
    'mb-4',
    'mb-6',
    'mb-2',
    'mt-8',
    'grid',
    'grid-cols-1',
    'md:grid-cols-3',
    'gap-6',
    'text-sm',
    'text-center',
    'bg-blue-500',
    'bg-blue-600',
    'hover:bg-blue-600',
    'hover:bg-blue-700',
    'transition',
    'duration-300'
  ]
}
